In [1]:
price = 2
qty = 3

In [3]:
total = price * qty
total

6

6

In [4]:
print(total)

6


In [7]:
mat1 = [1, 2, 3]
mat2 = [4, 5, 6]

In [10]:
def lin_multiply(mat1, mat2):
  result = []
  for x,y in zip(mat1, mat2):
    result.append(x*y)
  return result


In [11]:
res = lin_multiply(mat1, mat2)

In [12]:
res

[4, 10, 18]

In [4]:
import numpy as np

In [14]:
arr1 = np.array(mat1)
arr2 = np.array(mat2)

In [16]:
arr1, arr2

(array([1, 2, 3]), array([4, 5, 6]))

In [17]:
np.dot(arr1, arr2)

32

In [18]:
arr1 * arr2

array([ 4, 10, 18])

In [19]:
mat1 * mat2

TypeError: can't multiply sequence by non-int of type 'list'

In [22]:
arr3 = np.array(range(1, 13))

In [24]:
arr4 = np.resize(arr3, (4, 3))

# arr3.resize(4, 3)
# does in place resize

In [25]:
print(arr4)
print(arr3)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
